<?php
ob_start(); // start output buffer
include('light_status.php');
ob_end_clean(); // clean output buffer - this means current status will not be echo'd

$newline="\n\n";

$page='<!-- Generated by PHP because it\'s better than what I had before yo -->'.$newline; // open html tag and init page var
$page .= '<html lang="en">'.$newline;

// define the header
$head = <<< PAGEHEAD
<!-- Start of head -->
<head>
    <title>Alex's Pi - Light Control</title>
    
    <!-- Import Jquery incase I need it -->
    <script src = 'jquery-min.js' ></script >
    
    <!-- Styles -->
    <link rel = 'stylesheet' type = 'text/css' href = '../styles/style.css'/>
</head>
<!-- End of head -->
PAGEHEAD;
$page .= $head.$newline; // add the header to the page

$break = '<br><br><span class="sexy_line"></span><br><br>'; // define what a break looks like

$body = "<!-- Start of body -->\n";
$body .= '<body>'; // open the body tag
$body .= '<div class="center">'; // open center div

$title = <<< TITLE
<div class='title'>
    <p> Alex's Pi - Light Control </p>
    <a href=".." class="homeButton">Back home</a>
</div>
TITLE;
$body .= $title.$newline; // Add title to the body

$body .= $break.$newline; // LINE BREAK

function updateChangeTime() {
    $timeLastChanged=file_get_contents('light-changetime.txt');
    return $timeLastChanged;
}

$timeLastChanged=updateChangeTime(); // update variables
$status=ucfirst(getLightStatus());

// define info section
$info = <<< INFO
<div class='info'>

    <div class="statusholder">
        <p class="lightstatus" style = "" > Status: $status</p>
    </div >
    
    <div class="spacer">&nbsp</div>
    
    <div class="statusholder2">
        <p id="timelastchanged" style = "font-size:5vmin" class="timelastchanged" >$timeLastChanged</p>
    </div>

</div>
INFO;
$body .= $info.$newline; // add info to the body

$body .= $break.$newline; // LINE BREAK

// define button section
$buttons = <<< BUTTONS
<div class="buttons">
    <form action = "on.php">
        <input type = "submit" value = "Light on" class="on" > 
    </form> 
    
    <form action = "off.php">
        <input type = "submit" value = "Light off" class="off"> 
    </form>
</div>
BUTTONS;
$body .= $buttons.$newline; // add buttons to the body

$body .= $break.$newline; // LINE BREAK

$ip = $_SERVER['REMOTE_ADDR'];
$credit = <<< CREDIT
<div class="credit">
    <p>
        Your local IP: $ip    
        <br><br>
        Alex Fayers - 2019
    </p>
</div >
CREDIT;
$body .= $credit.$newline; // add credit to the body

$body .= '</div>'.$newline; // close center div
$body .= '</body>'; // close body
$body .= "\n<!-- End of body -->".$newline;

$page .= $body; // add body to the page
$page .= '</html>'; // close html tag

echo $page; // display page